/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import maps.MapsControl;

/**
 *
 * @author erksm
 */
public class PanelMapa extends javax.swing.JPanel {

    /**
     * Creates new form panelMapa
     */
    public static MapsControl controlMapa = new MapsControl();
    
    
    public PanelMapa() {
        initComponents();
        double latitud, longitud;
        latitud = 40.0;
        longitud = 110.0;
        controlMapa.crearDoc();
        controlMapa.generarHTML(latitud, longitud);
        controlMapa.overwriteHTML();
        controlMapa.abrirBrowser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(1290, 770));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
