/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.util.Calendar;
import java.util.Date;
import javax.swing.SpinnerNumberModel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

/**
 *
 * @author erksm
 */
public class PanelSismos extends javax.swing.JPanel {

    /**
     * Creates new form panelSismos
     */
    
    public PanelSismos() {
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateFechaSismo = new com.toedter.calendar.JDateChooser();
        lbFechaSismo = new javax.swing.JLabel();
        lbSismos2 = new javax.swing.JLabel();
        txtLatitud = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtLongitud = new javax.swing.JTextField();
        lbSismos9 = new javax.swing.JLabel();
        timeHoraSismo = new javax.swing.JSpinner();
        lbHoraSismo = new javax.swing.JLabel();
        lbSismos4 = new javax.swing.JLabel();
        SpinnerNumberModel sm =
        new SpinnerNumberModel(0.0, -1000.0, 1000.0, 0.1);
        numberProfundidad = new javax.swing.JSpinner(sm);
        panelRadioZonaSismo = new javax.swing.JPanel();
        rbTerrestre = new javax.swing.JRadioButton();
        rbMaritimo = new javax.swing.JRadioButton();
        lbSismos5 = new javax.swing.JLabel();
        lbSismos1 = new javax.swing.JLabel();
        cboProvincias = new javax.swing.JComboBox<>();
        cbFallas = new javax.swing.JComboBox<>();
        lbSismos6 = new javax.swing.JLabel();
        lbSignoMagnitud = new javax.swing.JLabel();
        txtMagnitud = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lbSismos11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSismos = new javax.swing.JTable();
        agregarPanel = new javax.swing.JPanel();
        btnAgregar1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1280, 560));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateFechaSismo.setBackground(new java.awt.Color(255, 255, 255));
        dateFechaSismo.setBorder(null);
        dateFechaSismo.setName("dateChooserFechaSismo"); // NOI18N
        add(dateFechaSismo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        lbFechaSismo.setBackground(new java.awt.Color(0, 0, 0));
        lbFechaSismo.setFont(new java.awt.Font("Roboto Slab Light", 1, 14)); // NOI18N
        lbFechaSismo.setForeground(new java.awt.Color(0, 0, 0));
        lbFechaSismo.setText("Fecha del Sismo");
        lbFechaSismo.setToolTipText("");
        add(lbFechaSismo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 50));

        lbSismos2.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos2.setFont(new java.awt.Font("Roboto Slab Light", 1, 14)); // NOI18N
        lbSismos2.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos2.setText("Latitud");
        lbSismos2.setToolTipText("");
        add(lbSismos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 30));

        txtLatitud.setBackground(new java.awt.Color(255, 255, 255));
        txtLatitud.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtLatitud.setForeground(new java.awt.Color(204, 204, 204));
        txtLatitud.setText("Ingrese la latitud del sismo");
        txtLatitud.setBorder(null);
        txtLatitud.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLatitudFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLatitudFocusLost(evt);
            }
        });
        txtLatitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtLatitudMousePressed(evt);
            }
        });
        add(txtLatitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 240, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 240, 20));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 240, 20));

        txtLongitud.setBackground(new java.awt.Color(255, 255, 255));
        txtLongitud.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtLongitud.setForeground(new java.awt.Color(204, 204, 204));
        txtLongitud.setText("Ingrese la longitud del sismo");
        txtLongitud.setBorder(null);
        txtLongitud.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLongitudFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLongitudFocusLost(evt);
            }
        });
        txtLongitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtLongitudMousePressed(evt);
            }
        });
        add(txtLongitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 240, 30));

        lbSismos9.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos9.setFont(new java.awt.Font("Roboto Slab Light", 1, 14)); // NOI18N
        lbSismos9.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos9.setText("Longitud");
        lbSismos9.setToolTipText("");
        add(lbSismos9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 130, 30));

        timeHoraSismo.setModel(new javax.swing.SpinnerDateModel());
        timeHoraSismo.setDoubleBuffered(true);
        timeHoraSismo.setEditor(new javax.swing.JSpinner.DateEditor(timeHoraSismo, "HH:mm:ss"));
        add(timeHoraSismo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 180, 30));

        lbHoraSismo.setBackground(new java.awt.Color(0, 0, 0));
        lbHoraSismo.setFont(new java.awt.Font("Roboto Slab Light", 1, 14)); // NOI18N
        lbHoraSismo.setForeground(new java.awt.Color(0, 0, 0));
        lbHoraSismo.setText("Hora exacta");
        lbHoraSismo.setToolTipText("");
        add(lbHoraSismo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 170, 50));

        lbSismos4.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos4.setFont(new java.awt.Font("Roboto Slab Light", 1, 14)); // NOI18N
        lbSismos4.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos4.setText("Profundidad KM");
        lbSismos4.setToolTipText("");
        add(lbSismos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 130, 50));

        numberProfundidad.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        numberProfundidad.setBorder(null);
        add(numberProfundidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 220, 30));

        panelRadioZonaSismo.setBackground(new java.awt.Color(255, 255, 255));
        panelRadioZonaSismo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rbTerrestre.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        rbTerrestre.setText("Terrestre");

        rbMaritimo.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        rbMaritimo.setText("Marítima");
        rbMaritimo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbMaritimoStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelRadioZonaSismoLayout = new javax.swing.GroupLayout(panelRadioZonaSismo);
        panelRadioZonaSismo.setLayout(panelRadioZonaSismoLayout);
        panelRadioZonaSismoLayout.setHorizontalGroup(
            panelRadioZonaSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadioZonaSismoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelRadioZonaSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbMaritimo, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(rbTerrestre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelRadioZonaSismoLayout.setVerticalGroup(
            panelRadioZonaSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRadioZonaSismoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbMaritimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbTerrestre)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        add(panelRadioZonaSismo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 160, 60));

        lbSismos5.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos5.setFont(new java.awt.Font("Roboto Slab Light", 1, 14)); // NOI18N
        lbSismos5.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos5.setText("Zona del Sismo");
        lbSismos5.setToolTipText("");
        add(lbSismos5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 130, 50));

        lbSismos1.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos1.setFont(new java.awt.Font("Roboto Slab Light", 1, 14)); // NOI18N
        lbSismos1.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos1.setText("Provincia");
        lbSismos1.setToolTipText("");
        add(lbSismos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 130, 50));

        cboProvincias.setBackground(new java.awt.Color(255, 255, 255));
        cboProvincias.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        cboProvincias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "San José", "Alajuela", "Cartago", "Heredia", "Guanacaste", "Puntarenas", "Limón" }));
        add(cboProvincias, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, 170, -1));

        cbFallas.setBackground(new java.awt.Color(255, 255, 255));
        cbFallas.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        cbFallas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Subducción ", "Choque de placas ", "Tectónico por falla local ", "Intra placa ", "Deformación Interna" }));
        add(cbFallas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 70, 240, -1));

        lbSismos6.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos6.setFont(new java.awt.Font("Roboto Slab Light", 1, 14)); // NOI18N
        lbSismos6.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos6.setText("Falla");
        lbSismos6.setToolTipText("");
        add(lbSismos6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 130, 50));

        lbSignoMagnitud.setBackground(new java.awt.Color(0, 0, 0));
        lbSignoMagnitud.setFont(new java.awt.Font("Roboto Slab Light", 1, 14)); // NOI18N
        lbSignoMagnitud.setForeground(new java.awt.Color(0, 0, 0));
        lbSignoMagnitud.setText("M");
        lbSignoMagnitud.setToolTipText("");
        add(lbSignoMagnitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, 130, 30));

        txtMagnitud.setBackground(new java.awt.Color(255, 255, 255));
        txtMagnitud.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtMagnitud.setForeground(new java.awt.Color(204, 204, 204));
        txtMagnitud.setText("Ingrese la magnitud del sismo");
        txtMagnitud.setBorder(null);
        txtMagnitud.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMagnitudFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMagnitudFocusLost(evt);
            }
        });
        txtMagnitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMagnitudMousePressed(evt);
            }
        });
        txtMagnitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMagnitudKeyReleased(evt);
            }
        });
        add(txtMagnitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 240, 30));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 240, 20));

        lbSismos11.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos11.setFont(new java.awt.Font("Roboto Slab Light", 1, 14)); // NOI18N
        lbSismos11.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos11.setText("Magnitud");
        lbSismos11.setToolTipText("");
        add(lbSismos11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 130, 30));

        tableSismos.setBackground(new java.awt.Color(255, 255, 255));
        tableSismos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSismos.setSelectionBackground(new java.awt.Color(50, 200, 186));
        tableSismos.setShowGrid(true);
        jScrollPane1.setViewportView(tableSismos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 1270, 540));

        agregarPanel.setBackground(new java.awt.Color(0, 150, 136));
        agregarPanel.setPreferredSize(new java.awt.Dimension(250, 50));

        btnAgregar1.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        btnAgregar1.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregar1.setText("Agregar");
        btnAgregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregar1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout agregarPanelLayout = new javax.swing.GroupLayout(agregarPanel);
        agregarPanel.setLayout(agregarPanelLayout);
        agregarPanelLayout.setHorizontalGroup(
            agregarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregar1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        agregarPanelLayout.setVerticalGroup(
            agregarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregarPanelLayout.createSequentialGroup()
                .addComponent(btnAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(agregarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 140, 230, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtLatitudFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLatitudFocusGained
        if(txtLatitud.getText().equals("Ingrese la latitud del sismo")){
            txtLatitud.setText("");
        }
        txtLatitud.setForeground(Color.black);
    }//GEN-LAST:event_txtLatitudFocusGained

    private void txtLatitudFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLatitudFocusLost
        // TODO add your handling code here:
        if (txtLatitud.getText().isEmpty() == true){
            txtLatitud.setText("Ingrese la latitud del sismo");
            txtLatitud.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtLatitudFocusLost

    private void txtLatitudMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLatitudMousePressed
        // TODO add your handling code here:
        if(txtLatitud.getText().equals("Ingrese la latitud del sismo")){
            txtLatitud.setText("");
        }
        txtLatitud.setForeground(Color.black);
    }//GEN-LAST:event_txtLatitudMousePressed

    private void txtLongitudFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLongitudFocusGained
        // TODO add your handling code here:
        if(txtLongitud.getText().equals("Ingrese la longitud del sismo")){
            txtLongitud.setText("");
        }
        txtLongitud.setForeground(Color.black);
    }//GEN-LAST:event_txtLongitudFocusGained

    private void txtLongitudFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLongitudFocusLost
        // TODO add your handling code here:
        if (txtLongitud.getText().isEmpty() == true){
            txtLongitud.setText("Ingrese la longitud del sismo");
            txtLongitud.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtLongitudFocusLost

    private void txtLongitudMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLongitudMousePressed
        // TODO add your handling code here:
        if(txtLongitud.getText().equals("Ingrese la longitud del sismo")){
            txtLongitud.setText("");
        }
        txtLongitud.setForeground(Color.black);
    }//GEN-LAST:event_txtLongitudMousePressed

    private void rbMaritimoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbMaritimoStateChanged
        // TODO add your handling code here:
        if (rbMaritimo.isSelected()){
            cboProvincias.setEnabled(false);
        }else{
            cboProvincias.setEnabled(true);
        }
    }//GEN-LAST:event_rbMaritimoStateChanged

    private void txtMagnitudFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMagnitudFocusGained
        // TODO add your handling code here:
        if(txtMagnitud.getText().equals("Ingrese la magnitud del sismo")){
            txtMagnitud.setText("");
        }
        txtMagnitud.setForeground(Color.black);
    }//GEN-LAST:event_txtMagnitudFocusGained

    private void txtMagnitudFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMagnitudFocusLost
        // TODO add your handling code here:
        if (txtMagnitud.getText().isEmpty() == true){
            txtMagnitud.setText("Ingrese la magnitud del sismo");
            txtMagnitud.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtMagnitudFocusLost

    private void txtMagnitudMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMagnitudMousePressed
        // TODO add your handling code here:
        if(txtMagnitud.getText().equals("Ingrese la magnitud del sismo")){
            txtMagnitud.setText("");
        }
        txtMagnitud.setForeground(Color.black);
    }//GEN-LAST:event_txtMagnitudMousePressed

    private void txtMagnitudKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMagnitudKeyReleased
        try {
            //  Block of code to try
            double val = Double.parseDouble(txtMagnitud.getText());
            System.out.println(val);
            if(2.0 <= val && val <= 6.9){
                lbSignoMagnitud.setText("Ml");
            }else if(val>6.9){
                lbSignoMagnitud.setText("Mw");
            }else{
                lbSignoMagnitud.setText("M");
            }
        }catch(Exception e) {
            //  Block of code to handle errors
        }
    }//GEN-LAST:event_txtMagnitudKeyReleased

    private void btnAgregar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregar1MouseClicked
        // TODO add your handling code here:

        DateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd hh:mm:ss");
        Calendar fechaSismo = Calendar.getInstance();
        Calendar hora = Calendar.getInstance();
        Date horaSismo = new Date();
        double profundidad =0, latitud=0, longitud=0, magnitud=0;
        boolean terrestre = false;
        int provincia =0 , origenFalla;

        //Obtener los datos de los campos
        fechaSismo = dateFechaSismo.getCalendar();
        horaSismo = (Date) timeHoraSismo.getValue();
        hora.setTime(horaSismo);
        profundidad = (double) numberProfundidad.getValue();
        if(rbMaritimo.isSelected()){
            terrestre = false;
            provincia = -1;
        }else if (rbTerrestre.isSelected()){
            terrestre = true;
            provincia = cboProvincias.getSelectedIndex();
        }
        
        origenFalla= cbFallas.getSelectedIndex();
        try{
            latitud = Double.parseDouble(txtLatitud.getText());
            longitud = Double.parseDouble(txtLongitud.getText());
            magnitud  = Double.parseDouble(txtMagnitud.getText());
        }catch(Exception e) {
            //  Block of code to handle errors
        }
        
        //Validaci[on de los datos
        if (fechaSismo!=null && horaSismo!=null && profundidad !=0){    
            boolean respuesta =  VentanaPrincipal.controlador.agregarSismo(fechaSismo, hora, profundidad, latitud, longitud, magnitud, terrestre, 
                    VentanaPrincipal.controlador.obtenerOrigen(origenFalla), VentanaPrincipal.controlador.obtenerProvincia(provincia));
            if(respuesta){
                cargarTabla();
            }
        }
    }//GEN-LAST:event_btnAgregar1MouseClicked

    private void btnAgregar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregar1MouseEntered
        // TODO add your handling code here:
        agregarPanel.setBackground(VentanaPrincipal.overedColor);
    }//GEN-LAST:event_btnAgregar1MouseEntered

    private void btnAgregar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregar1MouseExited
        // TODO add your handling code here:
        agregarPanel.setBackground(VentanaPrincipal.normalColor);
    }//GEN-LAST:event_btnAgregar1MouseExited
    
    public void cargarTabla(){
        tableSismos.setModel(VentanaPrincipal.controlador.cargarSismos());
        tableSismos.setDefaultEditor(Object.class, null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel agregarPanel;
    private javax.swing.JLabel btnAgregar1;
    private javax.swing.JComboBox<String> cbFallas;
    private javax.swing.JComboBox<String> cboProvincias;
    private com.toedter.calendar.JDateChooser dateFechaSismo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbFechaSismo;
    private javax.swing.JLabel lbHoraSismo;
    private javax.swing.JLabel lbSignoMagnitud;
    private javax.swing.JLabel lbSismos1;
    private javax.swing.JLabel lbSismos11;
    private javax.swing.JLabel lbSismos2;
    private javax.swing.JLabel lbSismos4;
    private javax.swing.JLabel lbSismos5;
    private javax.swing.JLabel lbSismos6;
    private javax.swing.JLabel lbSismos9;
    private javax.swing.JSpinner numberProfundidad;
    private javax.swing.JPanel panelRadioZonaSismo;
    private javax.swing.JRadioButton rbMaritimo;
    private javax.swing.JRadioButton rbTerrestre;
    private javax.swing.JTable tableSismos;
    private javax.swing.JSpinner timeHoraSismo;
    private javax.swing.JTextField txtLatitud;
    private javax.swing.JTextField txtLongitud;
    private javax.swing.JTextField txtMagnitud;
    // End of variables declaration//GEN-END:variables
}
