/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JPanel;
import modelo.NProvincia;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel; 
import org.jfree.chart.JFreeChart; 
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset; 
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author ytces
 */
public class PanelPorProvincia extends javax.swing.JPanel {

    /**
     * Creates new form PanelGraficos
     */
    public PanelPorProvincia() {
        initComponents();
        JFreeChart barChart = ChartFactory.createBarChart(
         "Histograma",           
         "Cantidad",            
         "Provincias",            
         createDataset(),          
         PlotOrientation.VERTICAL,           
         true, true, false);
        ChartPanel chartPanel = new ChartPanel( barChart );
        cargarPanelCharts(chartPanel);
    }
    
    private void cargarPanelCharts(JPanel panel) {
        contentPanelCharts.removeAll();
        contentPanelCharts.add(panel);
        contentPanelCharts.repaint();
        contentPanelCharts.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanelCharts = new javax.swing.JPanel();
        lbMenuCharts = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1280, 560));
        setPreferredSize(new java.awt.Dimension(1280, 820));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentPanelCharts.setLayout(new java.awt.CardLayout());
        add(contentPanelCharts, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 1070, 590));

        lbMenuCharts.setFont(new java.awt.Font("Roboto Condensed", 0, 36)); // NOI18N
        lbMenuCharts.setForeground(new java.awt.Color(0, 0, 0));
        lbMenuCharts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMenuCharts.setText("Cantidad de sismos por provincia");
        lbMenuCharts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuChartsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMenuChartsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMenuChartsMouseExited(evt);
            }
        });
        add(lbMenuCharts, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void lbMenuChartsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuChartsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbMenuChartsMouseClicked

    private void lbMenuChartsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuChartsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbMenuChartsMouseEntered

    private void lbMenuChartsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuChartsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbMenuChartsMouseExited

    private CategoryDataset createDataset( ) {
      final String sanjose = "San Jose";        
      final String cartago = "Cartago";        
      final String heredia = "Heredia";        
      final String alajuela = "Alajuela";        
      final String puntarenas = "Puntarenas";        
      final String guanacaste = "Guanacaste";        
      final String limon = "Limón";
      final String provincias = "Provincias";
      final DefaultCategoryDataset dataset = new DefaultCategoryDataset( );

      dataset.addValue( VentanaPrincipal.controlador.consultarSismosProvincia(NProvincia.SAN_JOSE),sanjose, provincias);
      dataset.addValue( VentanaPrincipal.controlador.consultarSismosProvincia(NProvincia.CARTAGO) , cartago , provincias );
      dataset.addValue( VentanaPrincipal.controlador.consultarSismosProvincia(NProvincia.HEREDIA) , heredia , provincias );
      dataset.addValue( VentanaPrincipal.controlador.consultarSismosProvincia(NProvincia.ALAJUELA) , alajuela , provincias );
      dataset.addValue( VentanaPrincipal.controlador.consultarSismosProvincia(NProvincia.PUNTARENAS) , puntarenas , provincias );
      dataset.addValue( VentanaPrincipal.controlador.consultarSismosProvincia(NProvincia.GUANACASTE) , guanacaste , provincias );
      dataset.addValue( VentanaPrincipal.controlador.consultarSismosProvincia(NProvincia.LIMON) , limon , provincias );
      
      return dataset; 
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanelCharts;
    private javax.swing.JLabel lbMenuCharts;
    // End of variables declaration//GEN-END:variables
}
