/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.Controlador;
import java.awt.Color;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ytces
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public static Controlador controlador = new Controlador();
    public static Color overedColor = new Color(50, 200, 186);
    public static Color normalColor = new Color(0, 150, 136);

    public VentanaPrincipal() {
        initComponents();
    }

    public void cargarPanel(JPanel panel) {
        contentPanel.removeAll();
        contentPanel.add(panel);
        contentPanel.repaint();
        contentPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zonaSismo = new javax.swing.ButtonGroup();
        backgroundPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        sismosMenuPanel = new javax.swing.JPanel();
        lbMenuSismos = new javax.swing.JLabel();
        graficosMenuPanel = new javax.swing.JPanel();
        lbMenuCharts = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setForeground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setMaximumSize(new java.awt.Dimension(500, 580));
        backgroundPanel.setMinimumSize(new java.awt.Dimension(500, 580));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(600, 500));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPanel.setBackground(new java.awt.Color(49, 49, 74));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sismosMenuPanel.setBackground(new java.awt.Color(0, 150, 136));
        sismosMenuPanel.setPreferredSize(new java.awt.Dimension(250, 50));

        lbMenuSismos.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        lbMenuSismos.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuSismos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMenuSismos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipboard.png"))); // NOI18N
        lbMenuSismos.setText("SISMOS");
        lbMenuSismos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuSismosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMenuSismosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMenuSismosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout sismosMenuPanelLayout = new javax.swing.GroupLayout(sismosMenuPanel);
        sismosMenuPanel.setLayout(sismosMenuPanelLayout);
        sismosMenuPanelLayout.setHorizontalGroup(
            sismosMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbMenuSismos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sismosMenuPanelLayout.setVerticalGroup(
            sismosMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sismosMenuPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbMenuSismos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuPanel.add(sismosMenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 154, -1, -1));

        graficosMenuPanel.setBackground(new java.awt.Color(0, 150, 136));
        graficosMenuPanel.setPreferredSize(new java.awt.Dimension(250, 50));

        lbMenuCharts.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        lbMenuCharts.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuCharts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMenuCharts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipboard.png"))); // NOI18N
        lbMenuCharts.setText("Gráficos");
        lbMenuCharts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuChartsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMenuChartsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMenuChartsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout graficosMenuPanelLayout = new javax.swing.GroupLayout(graficosMenuPanel);
        graficosMenuPanel.setLayout(graficosMenuPanelLayout);
        graficosMenuPanelLayout.setHorizontalGroup(
            graficosMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbMenuCharts, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        graficosMenuPanelLayout.setVerticalGroup(
            graficosMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, graficosMenuPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbMenuCharts, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuPanel.add(graficosMenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        backgroundPanel.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 900));

        topPanel.setBackground(new java.awt.Color(0, 150, 136));

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1310, Short.MAX_VALUE)
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        backgroundPanel.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 1310, 50));

        contentPanel.setLayout(new java.awt.CardLayout());
        backgroundPanel.add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 1300, 850));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1602, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void lbMenuSismosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuSismosMouseClicked
        // TODO add your handling code here:
        PanelSismos panel = new PanelSismos();
        cargarPanel(panel);
        controlador.enviar();
    }//GEN-LAST:event_lbMenuSismosMouseClicked

    private void lbMenuSismosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuSismosMouseEntered
        // TODO add your handling code here:
        sismosMenuPanel.setBackground(overedColor);
    }//GEN-LAST:event_lbMenuSismosMouseEntered

    private void lbMenuSismosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuSismosMouseExited
        // TODO add your handling code here:
        sismosMenuPanel.setBackground(normalColor);
    }//GEN-LAST:event_lbMenuSismosMouseExited

    private void lbMenuChartsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuChartsMouseClicked
        // TODO add your handling code here:
        PanelPorOrigen panel = new PanelPorOrigen();
        cargarPanel(panel);
    }//GEN-LAST:event_lbMenuChartsMouseClicked

    private void lbMenuChartsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuChartsMouseEntered
        // TODO add your handling code here:
        graficosMenuPanel.setBackground(overedColor);
    }//GEN-LAST:event_lbMenuChartsMouseEntered

    private void lbMenuChartsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuChartsMouseExited
        // TODO add your handling code here:
        graficosMenuPanel.setBackground(normalColor);
    }//GEN-LAST:event_lbMenuChartsMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel graficosMenuPanel;
    private javax.swing.JLabel lbMenuCharts;
    private javax.swing.JLabel lbMenuSismos;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel sismosMenuPanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.ButtonGroup zonaSismo;
    // End of variables declaration//GEN-END:variables

}
